// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjAZ_HTNBNSl3dwonLrHzvFPAwsSnw_w',
    appId: '1:318226051372:web:ec0de5554698ef514c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    authDomain: 'proyectdriveme.firebaseapp.com',
    storageBucket: 'proyectdriveme.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6LctaWMhKPQ4YO-Qx_tdY067w20MkQXU',
    appId: '1:318226051372:android:7be146b278e32cfe4c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    storageBucket: 'proyectdriveme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsjDPE-JnIT48EntBIg8b0y6vj41A2TLo',
    appId: '1:318226051372:ios:4fbe2be9768ada934c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    storageBucket: 'proyectdriveme.appspot.com',
    iosBundleId: 'com.example.pruebaDriveme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsjDPE-JnIT48EntBIg8b0y6vj41A2TLo',
    appId: '1:318226051372:ios:bddd991dd684cda14c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    storageBucket: 'proyectdriveme.appspot.com',
    iosBundleId: 'com.example.pruebaDriveme.RunnerTests',
  );
}
